config/routes.rb
Rails.application.routes.draw do

  get 'all_products' => 'products#all_products'
  post 'products/fetch_product' => 'products#fetch_product'
  resources :products

   root 'products#all_products'

end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  validates :name,:price, :description, :presence => true
  validates_numericality_of :price
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all.order("created_at DESC")
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to root_path, notice: 'Product was successfully created.'
    else
       render :new
    end
  end

  def update
    if @product.update(product_params)
       redirect_to root_path, notice: 'Product was successfully updated.'
    else
       render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully destroyed.'
  end

  def all_products
    @products = Product.paginate(page: params[:page], per_page: 9).order("created_at DESC")
    respond_to do |format|
      format.html
      format.js
    end
  end

  def fetch_product
    @product = Product.find(params[:product_id])
    render :json => @product
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shopping</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to 'Shopping', root_path, :class=> 'brand' %>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Add Products", new_product_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="container">
    <%= yield %>
</div>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product, html: { multipart: true } do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_products_list.html.erb
<% @products.each do |product| %>
    <div class="span3" >
      <div class="well text-center product_div">
        <div>
          <%= link_to 'Quick View','#',:class=> "quick_view", :id => "product_#{product.id}", :onmouseover => "fetch_product('#{product.id}')" %>
        </div>
        <div class="product_image">
          <%= link_to image_tag(product.image_url(:large)), product_path(product) %>
        </div>
        <strong><%= product.name %></strong>
      </div>
    </div>
<% end %>

app/views/products/all_products.html.erb
<p id="notice"><%= notice %></p>

<h3 class="text-center">MEN'S FOOTWEAR</h3>

<div id="my-products" class="offset1">
  <%= render "products_list" %>
</div>

<!-- Modal Start -->
<div class="modal fade bs-example-modal myModal" tabindex="-1" role="dialog" aria-labelledby="registrationModal" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Product</h4>
      </div>
      <div class="modal-body">
        <div class="product_image">
          <%= image_tag '/images/fallback/large_default.png', :id => "image_place" %>
        </div>
        <p id="desc" >Product Description</p>
        <p><strong>Rs.<span id="price">4568</span></strong> </p>
      </div>
    </div>
  </div>
</div>
<!--Modal End -->

<div id="infinite-scrolling" style="display:none;">
  <%= will_paginate %>
</div>

<script>
     function fetch_product(product_id){
        $.ajax(
                {
                    dataType: "json",
                    cache: false,
                    type: 'post',
                    url: '/products/fetch_product?product_id='+product_id,
                    success: function(data)
                    {
                       $(".modal-title").html(data.name);
                       $("#desc").html(data.description);
                       $("#price").html(data.price);
                       $("#image_place").attr('src', data.image.large.url)
                       $('.myModal').modal('show');
                    }
                });

    };
</script>

app/views/products/all_products.js.erb
$('#my-products').append('<%= j render "products_list" %>');
<% if @products.next_page %>
    $('.pagination').replaceWith('<%= j will_paginate @products %>');
<% else %>
    $(window).off('scroll');
    $('.pagination').remove();
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', root_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.description %></td>
        <td><%= image_tag(product.image_url(:thumb)) %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/products/show.html.erb
<div class="span5">
    <h4><%= @product.name %></h4>
    <div class="product_image">
      <%= image_tag(@product.image_url(:large)) %>
    </div>

    <strong><%= @product.price %></strong>

    <p>
      <%= @product.description %>
    </p>

    <%= link_to 'Edit', edit_product_path(@product) %> |
    <%= link_to 'Back', root_path %>
</div>